import { useEffect, useState } from "react";
import type { PhotoData } from "../data/photos";

// Gallery/metadata for all photos lives in /data/photos.json (generated by
// tools/import_photos.py) and is fetched once — keeping a 371-photo manifest
// out of the JS bundle. Module-level cache: every consumer shares one request.
let cache: PhotoData | null = null;
let pending: Promise<PhotoData> | null = null;

export function loadPhotos(): Promise<PhotoData> {
  if (cache) return Promise.resolve(cache);
  if (!pending) {
    pending = fetch("/data/photos.json")
      .then((r) => {
        if (!r.ok) throw new Error(`photos.json ${r.status}`);
        return r.json();
      })
      .then((d: PhotoData) => (cache = d));
  }
  return pending;
}

/** Returns the photo manifest, or null on the very first frame while it loads
 *  (a local static file — typically settled before anything is on screen). */
export function usePhotos(): PhotoData | null {
  const [data, setData] = useState<PhotoData | null>(cache);
  useEffect(() => {
    if (!data) loadPhotos().then(setData).catch((e) => console.error("[photos]", e));
  }, [data]);
  return data;
}
