// generated by tools/build_manifest.py
export interface DepthHero { photo: string; web: string; depth: string; id: string }
export const heroes: DepthHero[] = [
  {
    "photo": "/photos/ANK09879.jpg",
    "web": "/web/ANK09879.jpg",
    "depth": "/depth/ANK09879__depth.png",
    "id": "ANK09879"
  },
  {
    "photo": "/photos/ANK00164.jpg",
    "web": "/web/ANK00164.jpg",
    "depth": "/depth/ANK00164__depth.png",
    "id": "ANK00164"
  },
  {
    "photo": "/photos/ANK01938.jpg",
    "web": "/web/ANK01938.jpg",
    "depth": "/depth/ANK01938__depth.png",
    "id": "ANK01938"
  },
  {
    "photo": "/photos/ANK09500.jpg",
    "web": "/web/ANK09500.jpg",
    "depth": "/depth/ANK09500__depth.png",
    "id": "ANK09500"
  },
  {
    "photo": "/photos/ANK09212.jpg",
    "web": "/web/ANK09212.jpg",
    "depth": "/depth/ANK09212__depth.png",
    "id": "ANK09212"
  },
  {
    "photo": "/photos/ANK08837.jpg",
    "web": "/web/ANK08837.jpg",
    "depth": "/depth/ANK08837__depth.png",
    "id": "ANK08837"
  },
  {
    "photo": "/photos/ANK03010.jpg",
    "web": "/web/ANK03010.jpg",
    "depth": "/depth/ANK03010__depth.png",
    "id": "ANK03010"
  },
  {
    "photo": "/photos/20160503_164015.jpg",
    "web": "/web/20160503_164015.jpg",
    "depth": "/depth/20160503_164015__depth.png",
    "id": "20160503_164015"
  }
];

export interface Pillar { key: string; no: string; title: string; blurb: string }
export const pillars: Pillar[] = [
  { key: "dark", no: "01", title: "After Dark", blurb: "Astro, light trails, the moon \u2014 the hours most cameras sleep." },
  { key: "long", no: "02", title: "The Long View", blurb: "Distance rendered as haze \u2014 ridgelines, canyons, the scale of land." },
  { key: "hard", no: "03", title: "Hard Lines", blurb: "Cities and structure \u2014 glass, grids and deliberate geometry." },
  { key: "far", no: "04", title: "Far Afield", blurb: "Places worth the journey \u2014 ruins, landmarks and far horizons." },
  { key: "speed", no: "05", title: "At Speed", blurb: "Machines, roads and motion held still for a thousandth of a second." },
  { key: "still", no: "06", title: "Held Still", blurb: "Negative space and quiet \u2014 sand, water, the frames between." },
];

export interface PhotoMeta { title?: string; location?: string; story?: string; year?: string; camera?: string; lens?: string; settings?: string; print?: boolean; depthId?: string }
export const meta: Record<string, PhotoMeta> = {
  "/web/20160503_164015.jpg": {
    "camera": "Samsung Galaxy S6",
    "year": "2016",
    "settings": "4mm · f/1.9 · 1/50s · ISO 500",
    "title": "Drift",
    "story": "Weightless and lit from within, going nowhere in particular.",
    "print": true,
    "depthId": "20160503_164015"
  },
  "/web/ANK00003.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "55mm · f/5.6 · 1/8000s · ISO 800",
    "title": "Balanced",
    "location": "American Southwest",
    "story": "A boulder that has been about to fall for ten thousand years.",
    "print": true
  },
  "/web/ANK00009.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/8000s · ISO 800",
    "title": "The Pile",
    "location": "American Southwest",
    "story": "Stone stacked by nothing but time and weather.",
    "print": true
  },
  "/web/ANK00014.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/8000s · ISO 800",
    "title": "Centre Line",
    "location": "American Southwest",
    "story": "The dashed line doing its best to organise the emptiness.",
    "print": true
  },
  "/web/ANK00017.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "79mm · f/5.6 · 1/8000s · ISO 800",
    "title": "Into the Mountains",
    "location": "American Southwest",
    "story": "The road commits to the mountains and stops apologising.",
    "print": true
  },
  "/web/ANK00049.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "170mm · f/6.3 · 1/8000s · ISO 800",
    "title": "Traffic, with a View",
    "location": "American Southwest",
    "story": "Even the traffic jam comes with a mountain range.",
    "print": true
  },
  "/web/ANK00153.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/8000s · ISO 800",
    "title": "Soft Horizon",
    "location": "White Sands, New Mexico",
    "story": "Where the white sand and the white sky agree to blur.",
    "print": true
  },
  "/web/ANK00158.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/8000s · ISO 640",
    "title": "Dune",
    "location": "White Sands, New Mexico",
    "story": "Gypsum sand, white as snow, rippled by a wind that's moved on.",
    "print": true
  },
  "/web/ANK00164.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "55mm · f/4.5 · 1/8000s · ISO 800",
    "title": "Alone in White",
    "location": "White Sands, New Mexico",
    "story": "One figure for scale, in a place that erases scale.",
    "print": true,
    "depthId": "ANK00164"
  },
  "/web/ANK00246.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "70mm · f/5.6 · 1/6400s · ISO 800",
    "title": "The Leaning Tower",
    "location": "Pisa, Italy",
    "story": "Eight centuries of slowly almost-falling, and still showing off.",
    "print": true
  },
  "/web/ANK00257.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "70mm · f/32 · 1/100s · ISO 800",
    "title": "Duomo",
    "location": "Pisa, Italy",
    "story": "The cathedral the famous tower was only ever meant to announce.",
    "print": true
  },
  "/web/ANK00285.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "70mm · f/5.6 · 1/2000s · ISO 800",
    "title": "The Colosseum",
    "location": "Rome, Italy",
    "story": "Where a city once went to watch itself, now watching us back.",
    "print": true
  },
  "/web/ANK00325.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2023",
    "settings": "28mm · f/9 · 25s · ISO 3200",
    "title": "First Stars",
    "story": "The blue hour gives up, and the first real stars arrive.",
    "print": true
  },
  "/web/ANK00330.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2023",
    "settings": "28mm · f/5 · 30s · ISO 3200",
    "title": "A Single Streak",
    "story": "One piece of rock, older than the planet, ending its run in a line.",
    "print": true
  },
  "/web/ANK00528-Pano.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2023",
    "settings": "70mm · f/5.6 · 1/1600s · ISO 400",
    "title": "Dawn Layers",
    "location": "The Alps",
    "story": "Morning sorts the mountains into layers, nearest to furthest.",
    "print": true
  },
  "/web/ANK00641.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2023",
    "settings": "165mm · f/6.3 · 1/1600s · ISO 320",
    "title": "Surface",
    "story": "Just water and light, agreeing to be enough.",
    "print": true
  },
  "/web/ANK00661.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2023",
    "settings": "210mm · f/6.3 · 1/1600s · ISO 800",
    "title": "Breach",
    "story": "Half a ton of muscle, choosing to leave the water for a second.",
    "print": true
  },
  "/web/ANK00685.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2023",
    "settings": "210mm · f/6.3 · 1/1600s · ISO 500",
    "title": "The Pod",
    "story": "They surface together, breathe together, and are gone together.",
    "print": true
  },
  "/web/ANK01596.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2024",
    "settings": "28mm · f/6.3 · 30s · ISO 4000",
    "title": "Gold",
    "story": "Autumn, defocused into pure colour.",
    "print": true
  },
  "/web/ANK01856.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2024",
    "settings": "70mm · f/5.6 · 1/320s · ISO 160",
    "title": "Green Walls",
    "location": "The Alps",
    "story": "Summer turns the slopes to felt; the cloud decides the mood.",
    "print": true
  },
  "/web/ANK01923.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2024",
    "settings": "28mm · f/3.5 · 30s · ISO 4000",
    "title": "Galactic Core",
    "story": "Looking straight into the bright heart of the galaxy we live in.",
    "print": true
  },
  "/web/ANK01925.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2024",
    "settings": "28mm · f/3.5 · 30s · ISO 4000",
    "title": "Night Over Stone",
    "story": "The sky does the moving; the rock has waited here for the show.",
    "print": true
  },
  "/web/ANK01938.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2024",
    "settings": "40mm · f/4 · 1/1250s · ISO 50",
    "title": "Königssee",
    "location": "Königssee, Bavaria",
    "story": "Still water, steep walls, and the kind of quiet you can hear.",
    "print": true,
    "depthId": "ANK01938"
  },
  "/web/ANK02304.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "52mm · f/5 · 1/800s · ISO 250",
    "title": "Snow Pass",
    "location": "The Alps",
    "story": "A pass that's only open for the brave and the well-tyred.",
    "print": true
  },
  "/web/ANK02315.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "70mm · f/5.6 · 1/500s · ISO 125",
    "title": "Descent",
    "location": "The Alps",
    "story": "A single paraglider, trusting the air over the snow.",
    "print": true
  },
  "/web/ANK02413.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "28mm · f/3.5 · 20s · ISO 6400",
    "title": "The Faint Arm",
    "story": "A spiral arm you only see once your eyes forget the city.",
    "print": true
  },
  "/web/ANK02673.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "67mm · f/5.6 · 1/160s · ISO 100",
    "title": "Minaret",
    "location": "Istanbul, Türkiye",
    "story": "A single spire, built to carry a voice across a whole city.",
    "print": true
  },
  "/web/ANK02676.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "70mm · f/5.6 · 1/160s · ISO 125",
    "title": "Blue Mosque at Dusk",
    "location": "Istanbul, Türkiye",
    "story": "Six minarets against the last blue of the day.",
    "print": true
  },
  "/web/ANK02879.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "70mm · f/6.3 · 1/1250s · ISO 1600",
    "title": "The Eye",
    "story": "The instrument the whole craft is really about.",
    "print": true
  },
  "/web/ANK02917-Pano.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "70mm · f/6.3 · 1/3200s · ISO 1600",
    "title": "Sun on the Water",
    "story": "The sun lays a path across the water it has no intention of keeping.",
    "print": true
  },
  "/web/ANK02923.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "70mm · f/6.3 · 1/3200s · ISO 1000",
    "title": "The Sinking Sun",
    "story": "The day's last decision, made in orange.",
    "print": true
  },
  "/web/ANK02940.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "70mm · f/6.3 · 1/1600s · ISO 1600",
    "title": "Last Light, Alone",
    "story": "One figure, the whole horizon, and a minute of good light left.",
    "print": true
  },
  "/web/ANK02998.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "70mm · f/6.3 · 1/8000s · ISO 1250",
    "title": "Carved Country",
    "location": "Cappadocia, Türkiye",
    "story": "A landscape that looks built, but only weather did this.",
    "print": true
  },
  "/web/ANK03002.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "191mm · f/6.3 · 1/6400s · ISO 1250",
    "title": "The Valley",
    "location": "Cappadocia, Türkiye",
    "story": "A valley carved soft, where people once lived inside the rock.",
    "print": true
  },
  "/web/ANK03010.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "210mm · f/6.3 · 1/6400s · ISO 1000",
    "title": "Fairy Chimneys",
    "location": "Cappadocia, Türkiye",
    "story": "Stone the wind has been sculpting since before anyone watched.",
    "print": true,
    "depthId": "ANK03010"
  },
  "/web/ANK03352.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "210mm · f/6.3 · 1/8000s · ISO 1600",
    "title": "Ridge Behind Ridge",
    "location": "The Alps",
    "story": "Distance made visible — the air itself becomes the subject.",
    "print": true
  },
  "/web/ANK03364.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "68mm · f/5 · 1/8000s · ISO 1600",
    "title": "Valley Light",
    "location": "The Alps",
    "story": "Late sun finds the one valley still holding colour.",
    "print": true
  },
  "/web/ANK03368.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "156mm · f/5.6 · 1/1600s · ISO 1000",
    "title": "The Ridge",
    "location": "The Alps",
    "story": "Ridge behind ridge, each one paler than the last.",
    "print": true
  },
  "/web/ANK03396.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "183mm · f/6.3 · 1/8000s · ISO 1600",
    "title": "Far Peaks",
    "location": "The Alps",
    "story": "The farthest peaks barely commit to being there at all.",
    "print": true
  },
  "/web/ANK03441.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "210mm · f/6.3 · 1/3200s · ISO 1600",
    "title": "What the Romans Left",
    "location": "Türkiye",
    "story": "Columns still standing for an audience that left two thousand years ago.",
    "print": true
  },
  "/web/ANK03458.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "210mm · f/6.3 · 1/3200s · ISO 1600",
    "title": "Relief",
    "location": "Türkiye",
    "story": "Carved faces worn nearly smooth, still insisting on being remembered.",
    "print": true
  },
  "/web/ANK03575.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "133mm · f/6.3 · 1/200s · ISO 100",
    "title": "Travertine",
    "location": "Pamukkale, Türkiye",
    "story": "Calcium and time, building a staircase the colour of cloud.",
    "print": true
  },
  "/web/ANK03580.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "162mm · f/8 · 1/250s · ISO 100",
    "title": "Terraces",
    "location": "Pamukkale, Türkiye",
    "story": "Mineral water cooling into white terraces, step by step, for millennia.",
    "print": true
  },
  "/web/ANK03670.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "209mm · f/6.3 · 1/3200s · ISO 1600",
    "title": "Full Moon",
    "story": "Close enough to count the seas, far enough to stay a mystery.",
    "print": true
  },
  "/web/ANK03675.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2025",
    "settings": "210mm · f/6.3 · 1/1000s · ISO 100",
    "title": "The Flag on the Hill",
    "location": "Türkiye",
    "story": "A flag on the headland, claiming the wind if nothing else.",
    "print": true
  },
  "/web/ANK03755-Enhanced-NR.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2025",
    "settings": "70mm · f/6.3 · 1/25s · ISO 1600",
    "title": "Marienplatz",
    "location": "Munich, Germany",
    "story": "The square Munich uses to keep its history within view.",
    "print": true
  },
  "/web/ANK03944.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2026",
    "settings": "60mm · f/5 · 1/20s · ISO 800",
    "title": "The Angel",
    "location": "Munich, Germany",
    "story": "Gold against a darkening sky — the city's quiet guardian.",
    "print": true
  },
  "/web/ANK03953.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2026",
    "settings": "210mm · f/6.3 · 1/500s · ISO 800",
    "title": "Half Light",
    "story": "The terminator line, where lunar day meets lunar night.",
    "print": true
  },
  "/web/ANK07505.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2021",
    "settings": "53mm · f/5.6 · 1/500s · ISO 250",
    "title": "Air-Cooled",
    "story": "A 911 the way they used to make them — cooled by nothing but the air it splits.",
    "print": true
  },
  "/web/ANK07684.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2021",
    "settings": "36mm · f/4 · 1/8000s · ISO 6400",
    "title": "Redline",
    "story": "The dials that only tell the truth at speed.",
    "print": true
  },
  "/web/ANK08090.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2021",
    "settings": "70mm · f/5.6 · 1/320s · ISO 6400",
    "title": "Ring of Light",
    "story": "A ring of light on dark water, doing nothing useful, perfectly.",
    "print": true
  },
  "/web/ANK08119.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2021",
    "settings": "28mm · f/3.5 · 1/160s · ISO 2500",
    "title": "Burst",
    "story": "A whole year's worth of patience, spent in three seconds.",
    "print": true
  },
  "/web/ANK08834.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "62mm · f/4.5 · 1/1250s · ISO 100",
    "title": "Empire",
    "location": "New York City",
    "story": "The building that taught the others how to stand.",
    "print": true
  },
  "/web/ANK08837.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "153mm · f/5.6 · 1/1000s · ISO 100",
    "title": "One World, From the Harbour",
    "location": "New York City",
    "story": "From the water, the city is just one tall idea.",
    "print": true,
    "depthId": "ANK08837"
  },
  "/web/ANK08909.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/1250s · ISO 100",
    "title": "Red Seam",
    "location": "New York City",
    "story": "A single red awning, holding a grey façade together.",
    "print": true
  },
  "/web/ANK08960.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "127mm · f/5.6 · 1/1250s · ISO 160",
    "title": "Straight Up",
    "location": "New York City",
    "story": "Looking up until the tower disappears into its own perspective.",
    "print": true
  },
  "/web/ANK08964-Pano.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "55mm · f/4.5 · 1/1250s · ISO 160",
    "title": "The Island",
    "location": "New York City",
    "story": "The most photographed skyline on earth, trying for an honest frame.",
    "print": true
  },
  "/web/ANK09062.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "28mm · f/3.5 · 1/4000s · ISO 6400",
    "title": "Grid",
    "location": "New York City",
    "story": "Windows by the thousand, each one somebody's afternoon.",
    "print": true
  },
  "/web/ANK09117.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "70mm · f/5.6 · 1/8000s · ISO 2500",
    "title": "The Park and the Towers",
    "location": "Central Park, New York City",
    "story": "The one rectangle of calm the city agreed to leave alone.",
    "print": true
  },
  "/web/ANK09153.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "70mm · f/6.3 · 1/8000s · ISO 3200",
    "title": "Bethesda",
    "location": "Central Park, New York City",
    "story": "The fountain that has watched a century of New Yorkers walk past.",
    "print": true
  },
  "/web/ANK09212.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "70mm · f/6.3 · 1/8000s · ISO 1600",
    "title": "Wing",
    "location": "The Oculus, New York City",
    "story": "Calatrava's bones — a station that wanted to be a bird.",
    "print": true,
    "depthId": "ANK09212"
  },
  "/web/ANK09220.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "70mm · f/6.3 · 1/8000s · ISO 1600",
    "title": "Inside the Rib",
    "location": "The Oculus, New York City",
    "story": "Inside the whale, where the light is rationed by rib.",
    "print": true
  },
  "/web/ANK09243.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/8000s · ISO 2000",
    "title": "Façade",
    "location": "New York City",
    "story": "Repetition, until it becomes a rhythm.",
    "print": true
  },
  "/web/ANK09313.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "70mm · f/6.3 · 1/8000s · ISO 6400",
    "title": "The Tower",
    "location": "New York City",
    "story": "Deco ambition, still pointing the way it was told to.",
    "print": true
  },
  "/web/ANK09346.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "55mm · f/6.3 · 1/3200s · ISO 400",
    "title": "Scree",
    "story": "The mountain, slowly becoming gravel.",
    "print": true
  },
  "/web/ANK09357.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/3200s · ISO 400",
    "title": "Grain",
    "story": "Rock close enough to read like wood grain.",
    "print": true
  },
  "/web/ANK09470-Enhanced-NR.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/500s · ISO 1000",
    "title": "One Bird Over the Canyon",
    "location": "Grand Canyon, Arizona",
    "story": "Scale, explained: one bird, and all of that behind it.",
    "print": true
  },
  "/web/ANK09500.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "55mm · f/5.6 · 1/1250s · ISO 1000",
    "title": "Canyon at First Light",
    "location": "Grand Canyon, Arizona",
    "story": "The first sun hits the far rim while the floor is still deciding to wake.",
    "print": true,
    "depthId": "ANK09500"
  },
  "/web/ANK09501.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "80mm · f/5.6 · 1/1250s · ISO 1000",
    "title": "The Rim",
    "location": "Grand Canyon, Arizona",
    "story": "A mile down and a billion years deep, lit for about four minutes.",
    "print": true
  },
  "/web/ANK09543-PANO.jpg": {
    "camera": "Sony α 7 II",
    "year": "2022",
    "settings": "68mm",
    "title": "Canyon Panorama",
    "location": "Grand Canyon, Arizona",
    "story": "The view that makes everyone go quiet at the same time.",
    "print": true
  },
  "/web/ANK09564-Pano.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/4000s · ISO 500",
    "title": "The Whole Canyon",
    "location": "Grand Canyon, Arizona",
    "story": "Too wide for one frame, so here are several, stitched.",
    "print": true
  },
  "/web/ANK09579.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/2500s · ISO 500",
    "title": "Red Walls",
    "location": "American Southwest",
    "story": "Iron in the rock, oxidised over ages into this exact red.",
    "print": true
  },
  "/web/ANK09731.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "70mm · f/5.6 · 1/6400s · ISO 400",
    "title": "The Switchback",
    "location": "American Southwest",
    "story": "The road gives up arguing with the mountain and just zigzags.",
    "print": true
  },
  "/web/ANK09748.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2022",
    "settings": "70mm · f/5.6 · 1/5000s · ISO 400",
    "title": "Through the Red",
    "location": "American Southwest",
    "story": "Driving through stone that was a seabed once.",
    "print": true
  },
  "/web/ANK09866.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/2500s · ISO 250",
    "title": "The Long Haul",
    "location": "American Southwest",
    "story": "Eighteen wheels and a horizon that never gets closer.",
    "print": true
  },
  "/web/ANK09879.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "55mm · f/5.6 · 1/2500s · ISO 640",
    "title": "Ridgelines into Haze",
    "location": "Gran Canaria, Canary Islands",
    "story": "Ridge dissolving into ridge until the island simply runs out.",
    "print": true,
    "depthId": "ANK09879"
  },
  "/web/ANK09947.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/4000s · ISO 800",
    "title": "Empty Road",
    "location": "American Southwest",
    "story": "One car, one road, and a desert that doesn't care either way.",
    "print": true
  },
  "/web/ANK09969.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/8000s · ISO 800",
    "title": "Joshua",
    "location": "American Southwest",
    "story": "The tree that named a desert, holding its arms up to nobody.",
    "print": true
  },
  "/web/ANK09994.jpg": {
    "camera": "Sony α 7 II",
    "lens": "E 55-210mm F4.5-6.3 OSS",
    "year": "2022",
    "settings": "210mm · f/6.3 · 1/8000s · ISO 800",
    "title": "Desert Two-Lane",
    "location": "American Southwest",
    "story": "Two lanes, no reason to hurry, every reason to keep going.",
    "print": true
  },
  "/web/DSC00247.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "48mm · ISO 2500",
    "title": "Arteries",
    "story": "Thirty seconds of shutter turns the traffic into the city's bloodstream.",
    "print": true
  },
  "/web/DSC00253.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "70mm · f/36 · 15s · ISO 50",
    "title": "Stop, Wait, Go",
    "story": "The three small suns every city agrees to obey.",
    "print": true
  },
  "/web/DSC00274-EDIT.jpg": {
    "year": "2020",
    "title": "The Fountain",
    "story": "The fountain throws light while the streets behind it stream past.",
    "print": true
  },
  "/web/DSC00427.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "54mm · f/5 · 1/160s · ISO 2500",
    "title": "Purple Dusk",
    "location": "The Alps",
    "story": "The five minutes when the snow goes violet and nobody's watching.",
    "print": true
  },
  "/web/DSC01660.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "41mm · f/4.5 · 1/1000s · ISO 125",
    "title": "The Falls",
    "location": "The Alps",
    "story": "Meltwater that was snow this morning, in a hurry to be a river.",
    "print": true
  },
  "/web/DSC01739.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "39mm · f/5.6 · 1/8000s · ISO 1600",
    "title": "Snowline",
    "location": "The Alps",
    "story": "Where the green gives up and the white takes over.",
    "print": true
  },
  "/web/DSC02274.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "70mm · f/13 · 1/320s · ISO 100",
    "title": "Low Tide",
    "story": "Two figures, the whole beach, and the tide somewhere else.",
    "print": true
  },
  "/web/DSC02774.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "54mm · f/5 · 1/50s · ISO 6400",
    "title": "Canal House, Midnight",
    "location": "Amsterdam, Netherlands",
    "story": "Amsterdam after the crowds, when the canal houses keep their own counsel.",
    "print": true
  },
  "/web/DSC02809.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "28mm · f/11 · 6s · ISO 50",
    "title": "Light, Written",
    "story": "Long exposure, the camera tossed — light signing its own name.",
    "print": true
  },
  "/web/DSC03852.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "50mm · f/5.6 · 1/80s · ISO 125",
    "title": "Glass, Looking Up",
    "location": "New York City",
    "story": "Steel and glass, leaning into the sky.",
    "print": true
  },
  "/web/DSC04086.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "70mm · f/5.6 · 1/60s · ISO 50",
    "title": "Lit Windows",
    "location": "New York City",
    "story": "A grid of lives, each window a different hour.",
    "print": true
  },
  "/web/DSC05009.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "28mm · f/3.5 · 1/400s · ISO 100",
    "title": "From the Window",
    "story": "The mountains you only ever meet from thirty thousand feet.",
    "print": true
  },
  "/web/DSC05199.jpg": {
    "camera": "Sony α 7 II",
    "lens": "FE 28-70mm F3.5-5.6 OSS",
    "year": "2020",
    "settings": "50mm · f/4.5 · 1/60s · ISO 100",
    "title": "The Edge of Glass",
    "location": "New York City",
    "story": "Where two glass walls meet the cloud and argue about who reflects it.",
    "print": true
  },
  "/web/IMG_20160811_235132.jpg": {
    "title": "Red Fort",
    "location": "Delhi, India",
    "story": "Mughal sandstone, lit at night, still holding the line.",
    "print": true
  }
};

export const galleries: Record<string, string[]> = {
  "dark": ["/web/20160503_164015.jpg", "/web/ANK00325.jpg", "/web/ANK00330.jpg", "/web/ANK01923.jpg", "/web/ANK01925.jpg", "/web/ANK02413.jpg", "/web/ANK03670.jpg", "/web/ANK03953.jpg", "/web/ANK08119.jpg", "/web/DSC00247.jpg", "/web/DSC00253.jpg", "/web/DSC00274-EDIT.jpg", "/web/DSC02774.jpg", "/web/DSC02809.jpg"],
  "long": ["/web/ANK00003.jpg", "/web/ANK00009.jpg", "/web/ANK00528-Pano.jpg", "/web/ANK01856.jpg", "/web/ANK01938.jpg", "/web/ANK02917-Pano.jpg", "/web/ANK02923.jpg", "/web/ANK02940.jpg", "/web/ANK03352.jpg", "/web/ANK03364.jpg", "/web/ANK03368.jpg", "/web/ANK03396.jpg", "/web/ANK09470-Enhanced-NR.jpg", "/web/ANK09500.jpg", "/web/ANK09501.jpg", "/web/ANK09543-PANO.jpg", "/web/ANK09564-Pano.jpg", "/web/ANK09579.jpg", "/web/ANK09731.jpg", "/web/ANK09748.jpg", "/web/ANK09879.jpg", "/web/ANK09969.jpg", "/web/DSC00427.jpg", "/web/DSC01660.jpg", "/web/DSC01739.jpg", "/web/DSC05009.jpg"],
  "hard": ["/web/ANK03755-Enhanced-NR.jpg", "/web/ANK03944.jpg", "/web/ANK08090.jpg", "/web/ANK08834.jpg", "/web/ANK08837.jpg", "/web/ANK08909.jpg", "/web/ANK08960.jpg", "/web/ANK08964-Pano.jpg", "/web/ANK09062.jpg", "/web/ANK09117.jpg", "/web/ANK09153.jpg", "/web/ANK09212.jpg", "/web/ANK09220.jpg", "/web/ANK09243.jpg", "/web/ANK09313.jpg", "/web/DSC03852.jpg", "/web/DSC04086.jpg", "/web/DSC05199.jpg"],
  "far": ["/web/ANK00246.jpg", "/web/ANK00257.jpg", "/web/ANK00285.jpg", "/web/ANK02673.jpg", "/web/ANK02676.jpg", "/web/ANK02998.jpg", "/web/ANK03002.jpg", "/web/ANK03010.jpg", "/web/ANK03441.jpg", "/web/ANK03458.jpg", "/web/ANK03575.jpg", "/web/ANK03580.jpg", "/web/ANK03675.jpg", "/web/IMG_20160811_235132.jpg"],
  "speed": ["/web/ANK00014.jpg", "/web/ANK00017.jpg", "/web/ANK00049.jpg", "/web/ANK00661.jpg", "/web/ANK00685.jpg", "/web/ANK02304.jpg", "/web/ANK07505.jpg", "/web/ANK07684.jpg", "/web/ANK09866.jpg", "/web/ANK09947.jpg", "/web/ANK09994.jpg"],
  "still": ["/web/ANK00153.jpg", "/web/ANK00158.jpg", "/web/ANK00164.jpg", "/web/ANK00641.jpg", "/web/ANK01596.jpg", "/web/ANK02315.jpg", "/web/ANK02879.jpg", "/web/ANK09346.jpg", "/web/ANK09357.jpg", "/web/DSC02274.jpg"],
};
