// generated by tools/import_photos.py — slim critical-path data.
// galleries + per-photo meta live in /data/photos.json (see lib/usePhotos).
export interface DepthHero { web: string; depth: string; id: string }
export const heroes: DepthHero[] = [
  {
    "web": "/web/ANK09879.jpg",
    "depth": "/depth/ANK09879__depth.png",
    "id": "ANK09879"
  },
  {
    "web": "/web/ANK00164.jpg",
    "depth": "/depth/ANK00164__depth.png",
    "id": "ANK00164"
  },
  {
    "web": "/web/ANK01938.jpg",
    "depth": "/depth/ANK01938__depth.png",
    "id": "ANK01938"
  },
  {
    "web": "/web/ANK09500.jpg",
    "depth": "/depth/ANK09500__depth.png",
    "id": "ANK09500"
  },
  {
    "web": "/web/ANK09212.jpg",
    "depth": "/depth/ANK09212__depth.png",
    "id": "ANK09212"
  },
  {
    "web": "/web/ANK08837.jpg",
    "depth": "/depth/ANK08837__depth.png",
    "id": "ANK08837"
  },
  {
    "web": "/web/ANK03010.jpg",
    "depth": "/depth/ANK03010__depth.png",
    "id": "ANK03010"
  },
  {
    "web": "/web/20160503_164015.jpg",
    "depth": "/depth/20160503_164015__depth.png",
    "id": "20160503_164015"
  }
];

export interface Pillar { key: string; no: string; title: string; blurb: string }
export const pillars: Pillar[] = [
  {
    "key": "dark",
    "no": "01",
    "title": "Night",
    "blurb": "Astro, light trails, the moon — the hours most cameras sleep."
  },
  {
    "key": "long",
    "no": "02",
    "title": "Nature",
    "blurb": "Distance rendered as haze — ridgelines, canyons, the scale of land."
  },
  {
    "key": "hard",
    "no": "03",
    "title": "City",
    "blurb": "Cities and structure — glass, grids and deliberate geometry."
  },
  {
    "key": "far",
    "no": "04",
    "title": "Travel",
    "blurb": "Places worth the journey — ruins, landmarks and far horizons."
  },
  {
    "key": "speed",
    "no": "05",
    "title": "Motion",
    "blurb": "Machines, roads and motion held still for a thousandth of a second."
  },
  {
    "key": "still",
    "no": "06",
    "title": "Patterns",
    "blurb": "Negative space and quiet — sand, water, the frames between."
  }
];

export interface PhotoMeta { title?: string; location?: string; story?: string; year?: string; camera?: string; lens?: string; settings?: string; print?: boolean; depthId?: string }
export interface PhotoData { pillars: Pillar[]; galleries: Record<string, string[]>; meta: Record<string, PhotoMeta> }
