/* GENERATED by site/tools/optimize_models.mjs — DO NOT EDIT BY HAND.
   Regenerate with `npm run models:optimize`.

   Measured from assets/models-src/modern_living_room.glb BEFORE the geometry was pruned, in world space with
   the scene's root matrix already applied (both sources are Z-up FBX exports
   whose root node carries a Z-up→Y-up rotation, so these are the Y-up numbers
   the runtime actually needs). Units are metres.
*/

import type { Vec3 } from "./sceneScript";

/** Where the original painting hung. The print wall's outward normal is +X, so
 *  a viewer facing it has their right hand toward [0, 0, -1]. */
export const PAINTING = {
  /** centre of the removed canvas quad */
  centre: [-2.8716, 2.637, 3.4356] as Vec3,
  normal: [1, 0, 0] as Vec3,
  up: [0, 1, 0] as Vec3,
  right: [0, 0, -1] as Vec3,
  /** the removed canvas was this big — 2.85 m tall, far larger than any print */
  width: 1.7637,
  height: 2.8487,
  /** plane offset along the normal (the wall face the print beds against) */
  planeX: -2.8716,
  /** the removed frame box, for reference */
  frame: { min: [-2.8817, 1.1654, 2.5015] as Vec3, max: [-2.8292, 4.1085, 4.3696] as Vec3 },
} as const;

/** Measured context, so hang height and camera shots can be reasoned about in
 *  real numbers instead of guessed. */
export const ROOM = {
  bounds: { min: [-3.0578, -0.0008, -2.9317] as Vec3, max: [3.0588, 5.9578, 8.7166] as Vec3 },
  wall:   { min: [-2.9051, 0.1028, -0.8701] as Vec3, max: [-2.8774, 4.6079, 8.7166] as Vec3 },
  floorY: 0.1028,
  /** sofa back top — the print must clearly clear this */
  couch:  { min: [-2.756, 0.0971, 1.4239] as Vec3, max: [0.7902, 0.9338, 6.1279] as Vec3 },
  rug:    { min: [-1.9062, 0.073, 2.411] as Vec3, max: [1.1964, 0.2143, 6.1511] as Vec3 },
  window: { min: [2.8693, 0.1028, 0.6928] as Vec3, max: [3.0588, 4.4779, 6.1796] as Vec3 },
  lamps:  { min: [-2.6025, 2.392, -0.2588] as Vec3, max: [-2.1152, 4.7324, 7.2957] as Vec3 },
} as const;
