/* ============================================================================
   roomScript — hand-tuned constants for the /prints living room.

   Same split cameraScript uses: roomPlacements.ts is MEASURED (regenerated by
   the model pipeline, never hand-edited), this file is TUNED by eye. Numbers
   here start from the measured ones and are then moved because the model's own
   choices are wrong for a print preview.
   ========================================================================== */

import type { Shot, Vec3 } from "./sceneScript";
import { PAINTING, ROOM } from "./roomPlacements";

export const ROOM_URL = "/models/modern_living_room.min.glb?v=1";

/**
 * Where the print hangs.
 *
 * NOT the painting's own centre. The removed painting was 2.85 m tall and hung
 * centred at y 2.64; a 60 cm print centred there would float absurdly above a
 * sofa whose back tops out at y {ROOM.couch.max[1]}. This is gallery practice
 * instead — centre about 1.45 m above the floor, which also puts the bottom
 * edge a comfortable margin above the sofa.
 *
 * x sits a hair in front of the wall face so the frame beds against it without
 * z-fighting. Keep the painting's z: the room's lamps and composition were
 * built around that spot.
 */
export const PRINT_WALL = {
  centre: [PAINTING.planeX + 0.0016, ROOM.floorY + 1.45, PAINTING.centre[2]] as Vec3,
  normal: PAINTING.normal as Vec3,
  up: PAINTING.up as Vec3,
  right: PAINTING.right as Vec3,
  /** free envelope on this wall — it is 4.5 m tall and 9.6 m long, so the only
   *  real constraint is not colliding with the sofa below or the ceiling above */
  maxW: 2.4,
  maxH: 2.6,
} as const;

export const ROOM_ANCHORS: Record<string, Vec3> = {
  print: PRINT_WALL.centre as Vec3,
  /** standing height in the middle of the seating area */
  room: [-0.4, 1.5, 4.0],
  sofa: [
    (ROOM.couch.min[0] + ROOM.couch.max[0]) / 2,
    ROOM.couch.max[1],
    (ROOM.couch.min[2] + ROOM.couch.max[2]) / 2,
  ],
};

/**
 * Three framings the viewer can switch between. Not a scroll story — /prints is
 * a configurator, and a customer who has to scroll six screens to compare two
 * frame colours is being made to work for it. The camera holds one framing while
 * every option is changed against it, with a few degrees of pointer parallax so
 * the room still feels inhabited.
 *
 * `dir` points from the focus out toward the camera. The wall's outward normal
 * is +X, so every camera sits at greater x than the print, inside the room.
 * These are starting values — tune by eye and paste back.
 */
export const ROOM_SHOTS: Shot[] = [
  /* Room — you are standing in a living room, and there is a print in it */
  { p: 0.0, focus: "print", dir: [3.976, 0.2, 2.164], dist: 4.55, fov: 55 },
  /* Wall — square on, sofa still in frame so the size means something */
  { p: 0.5, focus: "print", dir: [2.676, 0.05, 0.9], dist: 2.85, fov: 45 },
  /* Detail — close enough to read the frame profile, the mount and the paper */
  { p: 1.0, focus: "print", dir: [1.2, 0.02, 0.42], dist: 1.15, fov: 38 },
];

export interface RoomView {
  key: string;
  label: string;
  p: number;
}

/** The framing switcher shown in the configurator panel. */
export const ROOM_VIEW_LIST: RoomView[] = [
  { key: "room", label: "Room", p: 0 },
  { key: "wall", label: "Wall", p: 0.5 },
  { key: "detail", label: "Detail", p: 1 },
];

/** ?view=room|wall|detail opens on a given framing. */
export const ROOM_VIEWS: Record<string, number> = Object.fromEntries(
  ROOM_VIEW_LIST.map((v) => [v.key, v.p])
);

/* ---------------------------------------------------------- close-ups ------
   Per-finish detail shots, the way a print lab photographs its products: the
   corner where the mitre and the mount read, the edge where thickness and
   float-mounting read, the surface. Generated from the actual configured print
   rather than shot from a sample, so what you inspect is your photograph at the
   size and finish you picked.

   Positions are expressed in the print's own basis — (right, up, normal) in
   units of its HALF width/height — so a shot frames the same feature whether
   the print is 20 cm or 90 cm. detailShot() resolves them to world space.        */

export interface DetailView {
  key: string;
  label: string;
  /** focus point: multiples of half-width, half-height, and metres along normal */
  focusAt: [number, number, number];
  /** camera direction from the focus, in the same basis (normalised later) */
  dir: [number, number, number];
  /** metres back from the focus */
  dist: number;
  /** extra distance per metre of the print's half-width, so a 20 cm print and a
   *  90 cm one frame the same feature at a similar apparent size. A fixed
   *  distance put the camera inside a large print and filled the shot with
   *  photograph instead of product. */
  distPerHalfW: number;
  fov: number;
}

const CORNER: DetailView = {
  key: "corner",
  label: "Corner",
  focusAt: [0.88, 0.88, 0],
  dir: [0.5, 0.45, 1],
  dist: 0.3,
  distPerHalfW: 0.5,
  fov: 34,
};
const EDGE: DetailView = {
  key: "edge",
  label: "Edge",
  /* Oblique enough to show how thick the thing is, but still facing the print
     rather than sighting down its length — looking straight along a large print
     just fills the frame with photograph. */
  focusAt: [0.92, 0, 0],
  dir: [1.0, 0.2, 0.66],
  dist: 0.34,
  distPerHalfW: 0.55,
  fov: 32,
};
const SURFACE: DetailView = {
  key: "surface",
  label: "Surface",
  focusAt: [0.25, 0.18, 0],
  dir: [0.9, 0.14, 0.4],
  dist: 0.3,
  distPerHalfW: 0.45,
  fov: 30,
};
const HANGING: DetailView = {
  key: "hanging",
  label: "Float",
  /* Well off to the side, to show the gap between print and wall. */
  focusAt: [0.7, -0.15, 0],
  dir: [1.25, 0.16, 0.5],
  dist: 0.34,
  distPerHalfW: 0.5,
  fov: 32,
};

/** Which close-ups are worth offering, by finish type. */
export const DETAIL_VIEWS: Record<string, DetailView[]> = {
  print: [SURFACE],
  "box-frame": [CORNER, EDGE],
  canvas: [EDGE, SURFACE],
  "framed-canvas": [CORNER, HANGING],
  acrylic: [EDGE, HANGING],
  dibond: [EDGE, HANGING],
};

export interface PrintGeometry {
  centre: Vec3;
  right: Vec3;
  up: Vec3;
  normal: Vec3;
  /** outer half-extents of the whole assembly, metres */
  halfW: number;
  halfH: number;
}

/** Resolve a DetailView against the configured print's real geometry. */
export function detailShot(v: DetailView, g: PrintGeometry): Shot {
  const focus: Vec3 = [0, 0, 0];
  const dir: Vec3 = [0, 0, 0];
  const axes: [Vec3, number, number][] = [
    [g.right, v.focusAt[0] * g.halfW, v.dir[0]],
    [g.up, v.focusAt[1] * g.halfH, v.dir[1]],
    [g.normal, v.focusAt[2], v.dir[2]],
  ];
  for (const [axis, focusAmt, dirAmt] of axes) {
    for (let i = 0; i < 3; i++) {
      focus[i] += axis[i] * focusAmt;
      dir[i] += axis[i] * dirAmt;
    }
  }
  for (let i = 0; i < 3; i++) focus[i] += g.centre[i];
  return { p: 0, focus, dir, dist: v.dist + v.distPerHalfW * g.halfW, fov: v.fov };
}

/**
 * Nodes the model pipeline deletes. Re-checked at runtime as a safety net, by
 * NAME and not by material: `Black` and `GlassD1` are shared with six unrelated
 * objects (Plane_Black_0, D2_Black_0, D2.005_Black_0, D1.008_GlassD1_0,
 * D1.011_GlassD1_0, D3_GlassD1_0), so hiding by material would black those out.
 */
export const PAINTING_NODES = ["Painting", "Painting_Black_0", "Painting_Painting_0", "Painting_GlassD1_0"];

/** Lights. The GLB ships Spotlights_* meshes in the ceiling but no
 *  KHR_lights_punctual, so every light in this scene is ours. */
export const ROOM_LIGHTS = {
  ambient: 0.34,
  /** daylight through Window_Window_0 on the +x wall */
  window: { position: [3.0, 3.3, 3.2] as Vec3, color: "#cfe0ff", intensity: 1.5 },
  /** the picture light — the only shadow caster in the scene, because the drama
   *  it puts on the print is the entire point of the page. Sits just in front of
   *  the wall and above the print, aimed down at it (see PictureLight: the
   *  spotlight's target must be parented into the scene or it aims at the
   *  world origin). A tight cone, so it reads as a picture light rather than
   *  general room lighting. */
  picture: {
    position: [-2.35, 3.6, PAINTING.centre[2]] as Vec3,
    intensity: 16,
    angle: 0.45,
    penumbra: 0.65,
    distance: 7,
    /** softer than physical falloff so the bottom of a large print is not dark */
    decay: 1.4,
  },
  /** ModernLamps sits right beside the print; without this it reads as unlit */
  lamp: { position: [-2.3, 3.3, 3.5] as Vec3, color: "#ffd9a8", intensity: 3.5, distance: 3.4 },
} as const;
