#!/usr/bin/env python3
"""Copy selects/depth into site/public, make 1400px web versions (+ webp), emit photos.ts."""
import os, glob, shutil, subprocess, json
from concurrent.futures import ThreadPoolExecutor

# WebP cuts the gallery payload ~70%. The site serves it via <picture> with a
# .jpg fallback — but a <source> that 404s does NOT fall back, so every web .jpg
# MUST have a matching .webp. Generate it here (Pillow is already a venv dep for
# depth maps); warn loudly if Pillow is missing so the gallery never breaks.
try:
    from PIL import Image
    HAVE_PIL = True
except ImportError:
    HAVE_PIL = False

ROOT = os.path.expanduser("~/photography_portfolio")
SEL = f"{ROOT}/assets/selects"
DEP = f"{ROOT}/assets/depth"
PUB = f"{ROOT}/site/public"

os.makedirs(f"{PUB}/photos", exist_ok=True)
os.makedirs(f"{PUB}/web", exist_ok=True)
os.makedirs(f"{PUB}/depth", exist_ok=True)

selects = sorted(glob.glob(f"{SEL}/*.jpg"))

def prep(src):
    name = os.path.basename(src)
    full = f"{PUB}/photos/{name}"
    web = f"{PUB}/web/{name}"
    if not os.path.exists(full):
        shutil.copy(src, full)
    if not os.path.exists(web):
        subprocess.run(["sips", "-s", "format", "jpeg", "-s", "formatOptions", "78",
                        "-Z", "1400", src, "--out", web], capture_output=True)
    webp = f"{PUB}/web/{os.path.splitext(name)[0]}.webp"
    if HAVE_PIL and os.path.exists(web) and not os.path.exists(webp):
        Image.open(web).convert("RGB").save(webp, "WEBP", quality=80, method=6)

with ThreadPoolExecutor(max_workers=8) as ex:
    list(ex.map(prep, selects))

if not HAVE_PIL:
    print("WARNING: Pillow not installed — no .webp generated. The gallery's "
          "<picture> tags expect a .webp next to every .jpg. Run with the venv "
          "(tools/.venv/bin/python) or `pip install Pillow`, then re-run.")

for d in glob.glob(f"{DEP}/*.png"):
    dst = f"{PUB}/depth/{os.path.basename(d)}"
    if not os.path.exists(dst):
        shutil.copy(d, dst)

# manifest
groups = {}
for s in selects:
    name = os.path.basename(s)
    tag = name.split("__")[0]
    groups.setdefault(tag, []).append(name)

heroes = []
for d in sorted(glob.glob(f"{PUB}/depth/*.png")):
    dn = os.path.basename(d)
    photo = dn.replace("__depth.png", ".jpg")
    if os.path.exists(f"{PUB}/photos/{photo}"):
        heroes.append({"photo": f"/photos/{photo}", "web": f"/web/{photo}", "depth": f"/depth/{dn}", "id": photo.split("__")[1]})

ts = "// generated by tools/prep_site_assets.py\n"
ts += "export interface DepthHero { photo: string; web: string; depth: string; id: string }\n"
ts += "export const heroes: DepthHero[] = " + json.dumps(heroes, indent=2) + ";\n\n"
ts += "export const galleries: Record<string, string[]> = {\n"
for tag, names in sorted(groups.items()):
    paths = json.dumps([f"/web/{n}" for n in names])
    ts += f'  "{tag}": {paths},\n'
ts += "};\n"
os.makedirs(f"{ROOT}/site/src/data", exist_ok=True)
open(f"{ROOT}/site/src/data/photos.ts", "w").write(ts)
print("photos:", len(selects), "heroes:", len(heroes), "groups:", {k: len(v) for k, v in groups.items()})
